name = "JuliaRegistry"
uuid = "5ae2f6cd-9e01-4c95-af9b-9a8d21f67550"
repo = "https://github.com/colinxs/JuliaRegistry.git"

[packages]
393ab781-533d-4207-828b-ae5a02ad719c = { name = "NixSourcerer", path = "N/NixSourcerer" }
